virtualbox5: enable resource metrics -- XXX breaks vbox
Won't compile b/c of ComPtr using dynamic_cast leads to
error: ‘nsISupports’ is an ambiguous base of ‘Machine’.